#compose file without ci-cd pipeline
# services:
#   backend:
#     build: ./mern/backend  # Path to your backend Dockerfile
#     ports:
#       - "5050:5050"  # Expose backend port
#     networks:
#       - mern_network
#     environment:
#       - MONGO_URI=${MONGO_URI}
#       - PORT=5050
#     depends_on:
#       - mongodb  # Ensure MongoDB starts first


#   frontend:
#     build: ./mern/frontend  # Path to your frontend Dockerfile
#     ports:
#       - "5173:5173"  # Expose frontend port
#     networks:
#       - mern_network
#     environment:
#       - VITE_API_URL=http://${EC2_PUBLIC_IP}:5050
#     depends_on:
#       - backend  # Ensure backend starts first


#   mongodb:
#     image: mongo:latest  # Use the official MongoDB image
#     ports:
#       - "27017:27017"  # Expose MongoDB port (optional for external access)
#     networks:
#       - mern_network
#     volumes:
#       - mongo-data:/data/db  # Persist MongoDB data

# networks:
#   mern_network:
#     driver: bridge  # Create a bridge network for communication

# volumes:
#   mongo-data:
#     driver: local  # Persist MongoDB data locally


##compose file with ci-cd pipeline

services:
  backend:
    image: ${{ DOCKER_HUB_USERNAME }}/mern-backend:latest
    ports:
      - "5050:5050"
    networks:
      - mern_network
    environment:
      - MONGO_URI=${MONGO_URI}  # Will be set from GitHub Secrets
      - PORT=5050
    depends_on:
      - mongodb

  frontend:
    image: ${{ DOCKER_HUB_USERNAME }}/mern-frontend:latest
    ports:
      - "5173:5173"
    networks:
      - mern_network
    environment:
      - VITE_API_URL=http://${EC2_PUBLIC_IP}:5050  # Will be set from GitHub Secrets.
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local

