apiVersion: v1
kind: Service
metadata:
  name: mern-frontend
spec:
  selector:
    app: mern-frontend
  ports:
    - protocol: TCP
      port: 5173
  type: NodePort # Use NodePort for external access
