apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend
    spec:
      containers:
        - name: mern-frontend
          image: rasooltalha/mern-frontend:latest
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: "http://54.89.161.219:7070"
