name: CI/CD Pipeline

on:
  push:
    branches:
      - aws-containerization

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (Backend)
        run: |
          cd backend
          npm install

      - name: Run ESLint (Backend)
        run: |
          cd backend
          npm run lint

      - name: Run tests (Backend)
        run: |
          cd backend
          npm test

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          npm install

      - name: Run ESLint (Frontend)
        run: |
          cd frontend
          npm run lint

      - name: Run tests (Frontend)
        run: |
          cd frontend
          npm test

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mern-backend:latest ./backend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mern-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mern-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mern-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            # Pull the latest Docker images
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mern-backend:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mern-frontend:latest

            # Stop and remove existing containers
            docker-compose down

            # Start new containers with environment variabless
            export MONGO_URI=${{ secrets.MONGO_URI }}
            export EC2_PUBLIC_IP=${{ secrets.EC2_HOST }}
            docker-compose up -d
          "